version: '3.4'
services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile
        command: sleep infinity
        links:
            - mongo
        volumes: 
            - ..:/workspace:cached
    mongo:
        image: mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: setu
            MONGO_INITDB_ROOT_PASSWORD: setu